### ISSUE TITLE
Source code utilization without mentioning & Lincence is missing

### ISSUE THREAD

**Issue by plemeri** [Ayews/M3Net#1]
Hi, congratulations for your great work achieving state-of-the-art performances on several benchmarks.

However, I found that our source code was used in your repository without any mentioning on ReadMe page and there's no Licence for the source code. Our source code is under the MIT Licence, so you need to include our Licence for the part of your source code which have been brought from ours.

Yours - [dataloader.py](https://github.com/I2-Multimedia-Lab/M3Net/blob/master/data/dataloader.py) | [custom_transforms.py](https://github.com/I2-Multimedia-Lab/M3Net/blob/master/data/custom_transforms.py)
Ours - [dataloader.py](https://github.com/plemeri/InSPyReNet/blob/main/data/dataloader.py) | [custom_transforms.py](https://github.com/plemeri/InSPyReNet/blob/main/data/custom_transforms.py)

Keep up your good work and please understand other people's hard work.

**Comment by Ayews** [comment]
Thank you very much for your reminder. In fact, your work has been very inspiring to us, and we apologize for the inconvenience caused due to our lack of understanding of the certificate. We have added the following comments at the beginning of the two files you mentioned, and made instructions about dataset loading in the README.md. We wonder if this can solve the problem you encountered. Thank you again for your code contribution. 

\# --------------------------------------------------------
\# InSPyReNet
\# Copyright (c) 2021 Taehun Kim
\# Licensed under The MIT License 
\# https://github.com/plemeri/InSPyReNet
\# --------------------------------------------------------

**Comment by plemeri** [comment]
Thank you very much for your feedback! Closing the issue.
